f = open("post.txt", "w")
f.close()
print("Welcome! This will create the file post.py uses.")
text = input("What do you want to put in post.txt?")
f = open("post.txt", "a")
f.write(text)
f.close()